package com.example.practic.themes.sdk_4.practice_block.work_manager_2

import android.app.NotificationChannel
import android.app.NotificationManager
import android.content.Context
import android.os.Build
import androidx.core.app.NotificationCompat
import androidx.work.Worker
import androidx.work.WorkerParameters
import com.example.practic.R

class MyWork(context: Context, workerParams: WorkerParameters)

/** Worker — это специальный класс, предоставляемый библиотекой WorkManager,
который используется для выполнения асинхронных задач в фоне.

- context контекст приложения, который используется внутри работы, например,
для получения доступа к системным сервисам

- workerParams - содержит все параметры для текущей задачи
(например, ID работы, временные ограничения, переданные данные)*/
    : Worker(context, workerParams) {


    /**  именно в нем выполняются все фоновые операции,
    запланированные в WorkManager */
    override fun doWork(): Result {
        createNotification(
            "Background Task by Shahab",
            "This notification is generated by workManager"
        )
        return Result.success()
        /** Возвращаем результат успешной работы */
    }

    private fun createNotification(title: String, description: String) {

        val notificationManager =
            applicationContext
                /** applicationContext.getSystemService() — это метод, который позволяет получить доступ к
                системным сервисам Android. В данном случае мы запрашиваем сервис для уведомлений,
                используя Context.NOTIFICATION_SERVICE.*/
                .getSystemService(Context.NOTIFICATION_SERVICE) as NotificationManager


        /** Создание канала */
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            val notificationChannel =                           /** Приоритет канала (не слишком навязчиво, но и не игнорируется)*/
                NotificationChannel("101", "channel", NotificationManager.IMPORTANCE_DEFAULT)
            notificationManager.createNotificationChannel(notificationChannel)
        }

        /** Создание уведомления */
        val notificationBuilder = NotificationCompat.Builder(applicationContext, "101")
            .setContentTitle(title)
            .setContentText(description)
            .setSmallIcon(R.drawable.ic_launcher_background)

        notificationManager.notify(1, notificationBuilder.build())

    }
}